Update YAML files - 2025-08-18 03:31:32

diff --git a/images_yaml/kali.yaml b/images_yaml/kali.yaml
--- a/images_yaml/kali.yaml
+++ b/images_yaml/kali.yaml
@@ -1,4 +1,252 @@
-404: Not Foundpackages:
+image:
+  distribution: "kali"
+  release: kali-rolling
+
+source:
+  downloader: debootstrap
+  url: https://kali.download/kali/
+  same_as: sid
+  keys:
+  - |-
+    -----BEGIN PGP PUBLIC KEY BLOCK-----
+
+    mQINBGgBJJUBEADlMTZVDCjrSXIAuYfL3VZt8OoplUdw3mSPlhIjZQmIo2sdzvAF
+    EMSCQ+vWeD4VqV9tBtiVx6j8VSfyW18YHHAkvajWDRg5hPLf80wGxrtXYu+vj3Ri
+    5dOMhrl9fHKIifPOoV3pFTtOk0dB9lkcmtNzjWgwOJduLbjjraE1BBKqc0uaXDCa
+    RJnPYkQuJQcZxmZVFAo9NP7KSAL1zMvutAd0R3WeMaWpT22nGa3rJj4kj25zV6Kn
+    qGnv5kQaY2cTlQHnp6EbiLe5sCE7zIOp5CjwIJhyCyn4zT8KqGB8Sw8PEi9mYlSY
+    wbGzzfAAbBk7Y8xbmvRrkrHzU74jH0iMK566QVu2yl3Dz0hrlliV6vGn2ZWu7qmh
+    lwXSb+q4u46tDbFjdUjYJG2upx5vOm5SewD9snLB4YN2e2qDeQgY16AfpkJa51+u
+    PwTeDCbfuQu3irLWcGRZgpOBgsxqCtpZBmF6ED7L8tntoyjZ9WeB8FnTcv7hx5J1
+    IPCO4K5TvW0SX6ZKp1Jusbkn5hrrFTjOJHhIDVdioM/wYDKkqJ9e25oGAqPkJYRY
+    euonU1teK+EOLM7ZIbalhukrw0bgYl9UJRxQMLEhZzoiiCLLiv3oWHAQGFclP+1E
+    zXgbLBviFAU4+DMXfhA6vy8BmS9oTpleS1p3/EOwf2rX/yt4qF7IW9ZXuQARAQAB
+    tEBLYWxpIExpbnV4IEFyY2hpdmUgQXV0b21hdGljIFNpZ25pbmcgS2V5ICgyMDI1
+    KSA8ZGV2ZWxAa2FsaS5vcmc+iQJUBBMBCgA+FiEEgnyFafJRjMZ3/soa7WVGLsjV
+    5MUFAmgF7tkCGwMFCQWkfeUFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQ7WVG
+    LsjV5MXcjw//XeI6OXY7VcH+hXRcT7W49AwqRfmSaSEWs474G2DQR9UppzvkFCab
+    uiWl5jrlkeGbVFsiBruJfIlCdYMMnPk8gEm/SEhVRqcZVOjYCWcMlSVB6oU+6tgW
+    jKPPRDELiq7mTl8S4sEdvUxpsWoMqEQZ1+CsJsw+p+TARGNIrUUdL9hTOoOUpvue
+    nKNEEfzbKvLk2gj2tKOgr1HcDmVbbmRsL87+UYq1JvA0OzJ0KrhBdTZHJWchAJwa
+    p+UUog2XrzvXYXWBPfQLsNVkFirmVd1B5vonj3OeNlVU51YriRQ4P4onLrwlfha8
+    vUGeNJw/ihXTQFpvmF7fFSRa7Pr5YfWkDZ4BGuEB+kSycu2PMWCXXHdY++cMIlRf
+    uUg/wvzcwAkS99DJ0EAiOun0oypE5+r5HwfaI9IrJlgZMPlFctyBIGVg2DFZCdLH
+    VHG1Voq/CU2tgWvWyuHXHVlUiZiWJoj7BbVa88Gj+VyvB/md1xBh0ScmfH4uGgnX
+    hpLFPIVuR1SJYarovVmtFhAjbqbrAA4Q9utpOeOOVDMD5tuq856/lLh+SWPkRsUy
+    ZJTwz1Nh0rJ/UJOMSo4ljkkr53iR/IM4woAAaP+0hkZoIDSbVVW5Im1Yj461exl4
+    0ltMBMym2KZk/IFOTloSfW7hMmGlqaLfQEH1ryHefIIpkgKJa6WgVxCZAg0ET1TU
+    KAEQAKF6f35y8FLyKgegJTrAFsv2NoiTk/tmQ+mMOyi8y+KaplqjNLx8QBkzbeAm
+    UWtq1z6tGWVX2E9mYaqG1PnREsPMLfIU68WcmoA++lUM7aKlAJWckNfR5YOFPrZE
+    PCT4WGOSwQPA/thzgKCiF0YNhC7XNMFIsvmp6fetyQKccXY6dKIqdgzxgIgoBgy3
+    hVECsC+K+M4yyk37XHLZLwZhdfZ96Wy7civUNe9QgTtv/2x0rozMFyqOgMffg6pf
+    qKyoBbT4r3eWZU35TjIUzN8QHvhQxA1YqDf2YIHQr9V9Dz2KHjO8X1rMQ1sXN8XQ
+    7SHT2gcXhlNpQV4jwkian/H0UL4u95TImi323/G/QdVR3Txjg+A7jwKJc5Oqqqb8
+    M8XQBsckalO6ic6wrLf91iGTsW+x+fTYMx2z5Eqy6QETPKlMggjMwEVTCKr8Zpo1
+    FbDqWc7ITjAyanBFrXVBUMNaQym46vW09Xsz4QwCFljtzIcOZFM4UvcfQLFicieK
+    z6TU1CKSq0vE2vNZ3GxdTbkExsSwBCrtpFOzvCk6dQr7Jj6pMb9XmeUnogj78K1Y
+    m2Eh5/bavwRhfUFA5dGCBqbLSfFWILdLqSO5TYtvWqcNv9ztP2EHvbfhP3KtEclv
+    KBO9APwEkEAOBHLv5cicKnTVXicAllK7bSqikSDTzZJ1Yr0XABEBAAG0JkthbGkg
+    TGludXggUmVwb3NpdG9yeSA8ZGV2ZWxAa2FsaS5vcmc+iQJVBBMBCgA/AhsDBgsJ
+    CAcDAgYVCAIJCgsEFgIDAQIeAQIXgBYhBETGUTqOT7PTCHX3WO1ET/B9jQv2BQJl
+    wGpBBQkcDzCZAAoJEO1ET/B9jQv2G2AP/iZq0B5bUX2NM2raQUYUXu2czF1GCkxm
+    SgimiFbwRerHnghIYZCozExR0F01Hrkb65yL+s/m51xOXG0HZrNT/VUtcP/nkwHn
+    JqqDqoFIoXlqFJtp/5/rMcZ6E+xZhoTZ5xLXKQ06bdSInoa4vEdS2yn6oqxHwSv/
+    gaoDdvoIXX+q/HtThdnGJREJOuwyy9v7zjHT4ZJjmZqWmouHvaJrvz81CWGmHvCT
+    Dub7xnqC8lIIbiEV2JNzn4Fsno0H6V7n/r8LF87tSQWS14uqlTlX1d3X2RxbO7Xs
+    KX5wvBdIe7mfd7zNXR/6YaxbUl+QLP36yaWvkD7EMhnpnFBUwl9ruqVFW7Cidq2M
+    wXuEz5P/MGyfU8HlNqkvJjMP6Z0NkDI94b6JxTXXiEdEKTKk6n69HRQBboHE6RP+
+    7evSH6TG3433u+xEI7kn3EWhgLHks20sttHjJAM6Serr4gnUbCRlSE0gJMHol0Yc
+    lnlIbTcAxK9q/t+W+WIh+NVOqOVkp2NkTTIWylEBeSTEFzEKJiGB3mEnNShjOzMZ
+    vMV1XyKnmbqKzBTgNC+PGN1Qa6k5rzHJJxw5EuXRhFsIcemVR/DcYx6tJyaV0oL1
+    MiPQ6fU/p1GIZhURADVMzqcWCwtXsVv16TwdmGluc7CjBKqDFbiUPAbLtLZ8ZXqH
+    dL8JFgBd5FmHuQINBE9U1CgBEACgw4K3rIOeA1RrBoUuoXPORDZQO3UvJYwzmpG6
+    xiZVbsNsypGCXzXoCFbeoZeWkRPZAMr8LuenySLCTHbZxaQrZbt7zvtsoZfWMfST
+    yMhlbETXmkEIGROT7Nvp6ULbreqLDfqPECUSfB3h4/Q4BjpLEP3GLkd8nvNc77aE
+    XhtWCh9EY2avkgD1I8vTJEmj502bdKH4yF00ym8mk52TQ9aqrVk/0sLVcJg22OUi
+    ax6a6AuWgoit2nABwcnpeqHIjki6N+2ZR83qEvfcwCXfgC7L/gSVQVT0OO9YjuW7
+    5Hs/yN0NAHcLXT96luZG7u+q1E1Qx/ur4wRFlAI+qfvmo7w/jMYYd0OFVFCMCV5/
+    HpQu+FGUt8KSOtKumccUZxgvM9dC7G6FIu9nIKcmsbVeaAsHlIAU/EgrWgHJ2pk5
+    g+w8YplK8wekE+/3JHa0zrIGMHMFXf/BAJocP1inexkP1HFJa0C+Td7NGNCifzVb
+    hLQnp1RkvaaiDuBbMOP2/jZwhXz3R7NLTvt2l4vZ9Jk5Svd8yszVk98kq57xKu+V
+    VVXXDJIDpXEGyzvWJZk0QcLmAP+B4LzrcVo7FcoVldbEP4x4z+GtR5+aPrt9DiuP
+    NOAoVG2K+ZIrOCADcV455QKDSBp0b2wYf+B/FOgDrVP/HERYTK7AmI7ZJVL+IGNC
+    d9yMMwARAQABiQI8BBgBCgAmAhsMFiEERMZROo5Ps9MIdfdY7URP8H2NC/YFAmXA
+    alIFCRwPMKoACgkQ7URP8H2NC/ZO3A//X9fUCmseuooRzYppzj9ikx+aWgezAgzf
+    Xd6ibaY+dlJFsSfsPXFSO10HR3LygMnoHJsufUU4wWPfxU02kuY0RvXxOa7GHZGW
+    4lBoYCiVFmco2spHw0Jy5sjC93j1AG6pGFFVhtstkPgSuztcRkYFxkEWHk8HBIXA
+    Bib0nqFO92m0nPFNzhvw5nvwySPaWCt4hQmZrSN7i6mPSXSf5Cn8eybeEqXkIA7P
+    auEORPAgDpU4PVNOB9cA608FAU4Cqah1COrunpR7hp+Zc+zAxeIDkW71vagxaMQB
+    t4E9G76uWhA/1rqBKxU9ZWvWhEaMuZm6gZm5/sNvBdy8nEhnnEcaBeJ+LV1fzbdp
+    zsNxk23y/GzmV/PWUFi7s77Q2iDVTDyrklG9lmirpuUKEKuv4hVW3gbwjc2Ay+sb
+    +48Aq2P/9YbzVyjP8trIho3KO3RkS6n2ZkeZBEFQPLOODhLObBLe2hR0pKp11Kgc
+    jU0PRuDTfhUBLcnCr+vwdQuboBZy0AcurVmjAH568tNXdaP3WYH+ZsWkhRHop5ax
+    NaBQJ2FDl6rNPYjaPTp09Fig4gbE4cuz8M29i0TlQs/bixuIGyz+6fsY2jhmQqTs
+    M7ywm9RRjEfiRPgMXoJx2xxX28nzZ+uer6DZ8EnTMNoYp1Yx8kNgJGtmKv7uKn9n
+    5L4BmZ/oTEg=
+    =EJtZ
+    -----END PGP PUBLIC KEY BLOCK-----
+  variant: minbase
+
+targets:
+  lxc:
+    create_message: |-
+      You just created a {{ image.description }} container.
+
+      To enable SSH, run: apt install openssh-server
+      No default root or user password are set by LXC.
+
+    config:
+    - type: all
+      before: 5
+      content: |-
+        lxc.include = LXC_TEMPLATE_CONFIG/debian.common.conf
+
+    - type: all
+      after: 4
+      content: |-
+        lxc.include = LXC_TEMPLATE_CONFIG/common.conf
+
+    - type: user
+      after: 4
+      content: |-
+        lxc.include = LXC_TEMPLATE_CONFIG/userns.conf
+
+    - type: all
+      content: |-
+        lxc.arch = {{ image.architecture_personality }}
+
+files:
+- path: /etc/hostname
+  generator: hostname
+
+- path: /etc/hosts
+  generator: hosts
+
+- path: /etc/resolvconf/resolv.conf.d/original
+  generator: remove
+
+- path: /etc/resolvconf/resolv.conf.d/tail
+  generator: remove
+
+- path: /etc/machine-id
+  generator: dump
+  content: uninitialized
+
+- path: /var/lib/dbus/machine-id
+  generator: remove
+
+- path: /etc/network/interfaces
+  generator: dump
+  content: |-
+    # This file describes the network interfaces available on your system
+    # and how to activate them. For more information, see interfaces(5).
+
+    # The loopback network interface
+    auto lo
+    iface lo inet loopback
+
+    auto eth0
+    iface eth0 inet dhcp
+
+    source /etc/network/interfaces.d/*.cfg
+  variants:
+  - default
+
+- name: meta-data
+  generator: cloud-init
+  variants:
+  - cloud
+
+- name: network-config
+  generator: cloud-init
+  variants:
+  - cloud
+
+- name: user-data
+  generator: cloud-init
+  variants:
+  - cloud
+
+- name: vendor-data
+  generator: cloud-init
+  variants:
+  - cloud
+
+packages:
+  manager: apt
+  update: true
+  cleanup: true
+  sets:
+  - packages:
+    - kali-archive-keyring
+    action: install
+    early: true
+
+  - packages:
+    - dialog
+    - init
+    - iproute2
+    - locales
+    - netbase
+    - net-tools
+    - openssh-client
+    - vim
+    - sudo
+    - systemd
+    action: install
+
+  - packages:
+    - cloud-init
+    - systemd-resolved
+    action: install
+    variants:
+    - cloud
+
+  - packages:
+    - ifupdown
+    - isc-dhcp-client
+    action: install
+    variants:
+    - default
+
+  repositories:
+  - name: sources.list
+    url: |-
+      deb http://kali.download/kali {{ image.release }} main contrib non-free non-free-firmware
+
+actions:
+- trigger: post-packages
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    # Make sure the locale is built and functional
+    echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
+    locale-gen en_US.UTF-8 UTF-8
+    update-locale LANG=en_US.UTF-8
+
+    # Cleanup underlying /run
+    mount -o bind / /mnt
+    rm -rf /mnt/run/*
+    umount /mnt
+
+    # Cleanup temporary shadow paths
+    rm /etc/*-
+
+- trigger: post-packages
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    # Enable cloud-init units
+    systemctl enable cloud-init-main.service cloud-init-local.service
+  variants:
+  - cloud
+
+ 
+mappings:
+  architecture_map: debian
+packages:
     - curl
     - wget
     - bash
@@ -6,9 +254,6 @@
     - sshpass
     - openssh-server
     - iptables
-    - dos2unix
-    - cron
-
 - trigger: post-files
   action: |-
     #!/bin/sh
@@ -53,3 +298,5 @@
   variants:
   - cloud
   - default
+    - dos2unix
+    - cron
